# Generated by Django 2.0.5 on 2018-10-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name_plural': '最新公告（如：开班信息）'},
        ),
        migrations.AlterModelTable(
            name='notice',
            table='Notice',
        ),
    ]
