# Generated by Django 2.0.5 on 2018-10-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_models', '0002_auto_20181018_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '课程'},
        ),
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='./static/images/icon/'),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(1, '上线'), (0, '下线')], default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='summary',
            field=models.CharField(default='summary', max_length=64),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(db_index=True, default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='course',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.IntegerField(choices=[(0, '不显示'), (1, '显示')], default=0),
        ),
        migrations.AlterModelTable(
            name='course',
            table='Course',
        ),
    ]
