# Generated by Django 2.1 on 2018-11-07 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_models', '0003_auto_20181018_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='company',
            field=models.CharField(default=None, max_length=32, verbose_name='就业公司'),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=32, unique=True, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='student',
            name='pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='./static/images/student_pic/', verbose_name='学员头像'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='salary',
            field=models.CharField(default=None, max_length=32, verbose_name='薪资'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(0, '下线'), (1, '上线')], default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='student',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='权重'),
        ),
    ]
