# Generated by Django 2.1 on 2018-11-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_models', '0006_auto_20181108_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bxslider',
            options={'verbose_name_plural': '首页轮播表'},
        ),
        migrations.AddField(
            model_name='bxslider',
            name='create_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='bxslider',
            name='href',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='bxslider',
            name='img',
            field=models.ImageField(default=None, upload_to='./static/images/focus/'),
        ),
        migrations.AddField(
            model_name='bxslider',
            name='status',
            field=models.IntegerField(choices=[(0, '上线'), (1, '下线')], default=0),
        ),
        migrations.AlterModelTable(
            name='bxslider',
            table='Bxslider',
        ),
    ]
