# Generated by Django 2.1 on 2018-11-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_models', '0007_auto_20181108_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bxslider',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
