# Generated by Django 2.1 on 2018-11-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_models', '0010_auto_20181108_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='./static/images/teacher_pic/', verbose_name='老师头像')),
                ('name', models.CharField(db_index=True, default=None, max_length=32, unique=True, verbose_name='姓名')),
                ('summary', models.CharField(default=None, max_length=256, verbose_name='简介')),
            ],
            options={
                'verbose_name_plural': '老师信息',
                'db_table': 'Teacher',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(0, '下线'), (1, '上线')], default=1),
        ),
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.IntegerField(choices=[(0, '不显示'), (1, '显示')], default=0),
        ),
    ]
