# Generated by Django 2.1 on 2018-11-13 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_models', '0012_classification_direction_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name_plural': '视频方向'},
        ),
        migrations.AlterModelTable(
            name='direction',
            table='Direction',
        ),
    ]
