# Generated by Django 2.1 on 2018-11-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_models', '0013_auto_20181113_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.IntegerField(choices=[(1, '显示'), (0, '不显示')], default=0),
        ),
    ]
