# Generated by Django 2.1 on 2018-11-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_models', '0014_auto_20181113_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='classification',
        ),
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.IntegerField(choices=[(0, '不显示'), (1, '显示')], default=0),
        ),
        migrations.DeleteModel(
            name='Direction',
        ),
    ]
