# Generated by Django 2.1 on 2018-11-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_models', '0015_auto_20181113_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0, verbose_name='权重（按从大到小排列）')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('classification', models.ManyToManyField(to='web_models.Classification')),
            ],
            options={
                'verbose_name_plural': '视频方向',
                'db_table': 'Direction',
            },
        ),
    ]
